task: MNIST
synthesizer: Pattern

random_seed: 42
batch_size: 256
test_batch_size: 512
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs: 1500
poison_epoch: 0
poison_epoch_stop: 1500
save_on_epochs: [] # [10, 20, 30, 40, 50]
optimizer: SGD
log_interval: 100

poisoning_proportion: 1.0
backdoor_label: 8

resume_model: 


save_model: True
log: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 20
fl_local_epochs: 2
fl_poison_epochs: 5
fl_total_participants: 200
fl_eta: 1
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.5

fl_number_of_adversaries: 4
fl_weight_scale: 5
fl_adv_group_size: 2
# fl_single_epoch_attack: 20

attack: ModelReplace
defense: FedAvg
fl_num_neurons: 8
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1